CREATE TABLE places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(20) NOT NULL,
    provider_place_id VARCHAR(100) NOT NULL,
    place_type VARCHAR(20) NOT NULL,
    name VARCHAR(200) NOT NULL,
    category_name VARCHAR(500),
    address_name VARCHAR(500) NOT NULL,
    road_address_name VARCHAR(500),
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    place_url VARCHAR(1000),
    CONSTRAINT uk_places_provider_place_id UNIQUE (provider, provider_place_id)
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_group VARCHAR(30) NOT NULL,
    code VARCHAR(50) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_tags_group_code UNIQUE (tag_group, code)
);

CREATE TABLE place_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    source VARCHAR(30) NOT NULL,
    confidence INTEGER NOT NULL,
    CONSTRAINT fk_place_tags_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_place_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id),
    CONSTRAINT uk_place_tags_place_tag UNIQUE (place_id, tag_id),
    CONSTRAINT ck_place_tags_confidence CHECK (confidence BETWEEN 0 AND 100)
);

CREATE INDEX idx_places_type_latitude_longitude
    ON places (place_type, latitude, longitude);

CREATE INDEX idx_place_tags_tag_place
    ON place_tags (tag_id, place_id);
