CREATE TABLE preference_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    allows_multiple_selection BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_preference_groups_code UNIQUE (code),
    CONSTRAINT ck_preference_groups_display_order CHECK (display_order >= 0)
);

CREATE TABLE preference_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preference_group_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_preference_options_group
        FOREIGN KEY (preference_group_id) REFERENCES preference_groups (id),
    CONSTRAINT uk_preference_options_group_code UNIQUE (preference_group_id, code),
    CONSTRAINT ck_preference_options_display_order CHECK (display_order >= 0)
);

CREATE TABLE activity_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_activity_categories_parent
        FOREIGN KEY (parent_id) REFERENCES activity_categories (id),
    CONSTRAINT uk_activity_categories_code UNIQUE (code),
    CONSTRAINT ck_activity_categories_display_order CHECK (display_order >= 0)
);

CREATE TABLE activity_search_terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_category_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    keyword VARCHAR(100) NOT NULL,
    search_priority INTEGER NOT NULL,
    is_fallback BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_activity_search_terms_category
        FOREIGN KEY (activity_category_id) REFERENCES activity_categories (id),
    CONSTRAINT uk_activity_search_terms_category_provider_keyword
        UNIQUE (activity_category_id, provider, keyword),
    CONSTRAINT ck_activity_search_terms_priority CHECK (search_priority >= 0)
);

CREATE TABLE activity_recommendation_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preference_option_id BIGINT NOT NULL,
    activity_category_id BIGINT NOT NULL,
    weight INTEGER NOT NULL,
    CONSTRAINT fk_activity_recommendation_rules_preference_option
        FOREIGN KEY (preference_option_id) REFERENCES preference_options (id),
    CONSTRAINT fk_activity_recommendation_rules_activity_category
        FOREIGN KEY (activity_category_id) REFERENCES activity_categories (id),
    CONSTRAINT uk_activity_recommendation_rules_option_category
        UNIQUE (preference_option_id, activity_category_id)
);

CREATE INDEX idx_preference_options_group_active_order
    ON preference_options (preference_group_id, is_active, display_order);

CREATE INDEX idx_preference_groups_active_order
    ON preference_groups (is_active, display_order);

CREATE INDEX idx_activity_categories_parent_active_order
    ON activity_categories (parent_id, is_active, display_order);

CREATE INDEX idx_activity_search_terms_category_active_priority
    ON activity_search_terms (activity_category_id, is_active, is_fallback, search_priority);

-- Initial recommendation catalogue. During the current development phase,
-- this baseline is intentionally maintained together with this schema migration.
INSERT INTO preference_groups (code, name, allows_multiple_selection, display_order)
VALUES
    ('COMPANION', '누구와 만나나요?', FALSE, 1),
    ('OCCASION', '어떤 자리인가요?', FALSE, 2),
    ('ENVIRONMENT', '어디가 좋나요?', FALSE, 3),
    ('ENERGY', '어떤 분위기가 좋나요?', TRUE, 4),
    ('HIGHLIGHT', '오늘 무엇을 가장 중요하게 생각하나요?', TRUE, 5),
    ('DATE_MOOD', '데이트 분위기를 더 골라볼까요?', TRUE, 6);

INSERT INTO preference_options (preference_group_id, code, name, display_order)
SELECT preference_group.id, option_seed.code, option_seed.name, option_seed.display_order
FROM preference_groups preference_group
JOIN (
    VALUES
        ('COMPANION', 'DATE', '데이트', 1), ('COMPANION', 'FRIENDS', '친구', 2),
        ('COMPANION', 'FAMILY', '가족', 3), ('COMPANION', 'SOLO', '혼자', 4),
        ('COMPANION', 'COLLEAGUES', '동료·모임', 5),
        ('OCCASION', 'CASUAL_OUTING', '가벼운 나들이', 1),
        ('OCCASION', 'SPECIAL_OCCASION', '특별한 날·기념일', 2),
        ('OCCASION', 'TOURISM', '지역 구경·관광', 3),
        ('ENVIRONMENT', 'INDOOR', '실내', 1), ('ENVIRONMENT', 'OUTDOOR', '야외', 2),
        ('ENERGY', 'QUIET', '조용한', 1), ('ENERGY', 'RELAXED', '편안한', 2),
        ('ENERGY', 'ACTIVE', '활동적인', 3), ('ENERGY', 'LIVELY', '신나는·북적이는', 4),
        ('HIGHLIGHT', 'CONVERSATION', '대화하기 좋은 곳', 1),
        ('HIGHLIGHT', 'UNIQUE_EXPERIENCE', '색다른 경험', 2),
        ('HIGHLIGHT', 'SIGHTS_AND_PHOTOS', '볼거리·사진', 3),
        ('HIGHLIGHT', 'TRENDY_PLACES', '요즘 인기 있는 곳', 4),
        ('DATE_MOOD', 'ROMANTIC', '로맨틱한', 1),
        ('DATE_MOOD', 'RELAXED', '편안한', 2), ('DATE_MOOD', 'ACTIVE', '활동적인', 3)
) AS option_seed(group_code, code, name, display_order)
    ON preference_group.code = option_seed.group_code;

INSERT INTO activity_categories (parent_id, code, name, display_order)
VALUES
    (NULL, 'CULTURE', '전시·문화', 1),
    (NULL, 'WORKSHOP', '공방·클래스', 2),
    (NULL, 'PLAY', '놀이·게임', 3),
    (NULL, 'SPORT', '스포츠·액티비티', 4),
    (NULL, 'OUTDOOR', '산책·자연', 5),
    (NULL, 'SHOPPING', '쇼핑·구경', 6),
    (NULL, 'HEALING', '휴식·힐링', 7),
    (NULL, 'SEASONAL_EVENT', '시즌·행사', 8);

INSERT INTO activity_search_terms (activity_category_id, provider, keyword, search_priority, is_fallback)
SELECT activity_category.id, term_seed.provider, term_seed.keyword, term_seed.search_priority, term_seed.is_fallback
FROM activity_categories activity_category
JOIN (
    VALUES
        ('CULTURE', 'KAKAO', '전시', 1, FALSE), ('CULTURE', 'KAKAO', '갤러리', 2, FALSE), ('CULTURE', 'KAKAO', '미술관', 3, TRUE),
        ('WORKSHOP', 'KAKAO', '공방', 1, FALSE), ('WORKSHOP', 'KAKAO', '원데이클래스', 2, FALSE), ('WORKSHOP', 'KAKAO', '도자기 공방', 3, TRUE),
        ('PLAY', 'KAKAO', '방탈출', 1, FALSE), ('PLAY', 'KAKAO', '보드게임', 2, FALSE), ('PLAY', 'KAKAO', '오락실', 3, TRUE),
        ('SPORT', 'KAKAO', '클라이밍', 1, FALSE), ('SPORT', 'KAKAO', '볼링장', 2, FALSE), ('SPORT', 'KAKAO', '실내 스포츠', 3, TRUE),
        ('OUTDOOR', 'KAKAO', '공원', 1, FALSE), ('OUTDOOR', 'KAKAO', '산책로', 2, FALSE), ('OUTDOOR', 'KAKAO', '한강공원', 3, TRUE),
        ('SHOPPING', 'KAKAO', '편집샵', 1, FALSE), ('SHOPPING', 'KAKAO', '쇼핑몰', 2, FALSE), ('SHOPPING', 'KAKAO', '전통시장', 3, TRUE),
        ('HEALING', 'KAKAO', '스파', 1, FALSE), ('HEALING', 'KAKAO', '찜질방', 2, FALSE), ('HEALING', 'KAKAO', '테라피', 3, TRUE),
        ('SEASONAL_EVENT', 'KAKAO', '팝업스토어', 1, FALSE), ('SEASONAL_EVENT', 'KAKAO', '플리마켓', 2, FALSE), ('SEASONAL_EVENT', 'KAKAO', '축제', 3, TRUE)
) AS term_seed(activity_category_code, provider, keyword, search_priority, is_fallback)
    ON activity_category.code = term_seed.activity_category_code;

INSERT INTO activity_recommendation_rules (preference_option_id, activity_category_id, weight)
SELECT preference_option.id, activity_category.id, rule_seed.weight
FROM (
    VALUES
        ('COMPANION','DATE','CULTURE',15), ('COMPANION','DATE','WORKSHOP',25), ('COMPANION','DATE','PLAY',6), ('COMPANION','DATE','SPORT',5), ('COMPANION','DATE','OUTDOOR',10), ('COMPANION','DATE','SHOPPING',10), ('COMPANION','DATE','HEALING',10), ('COMPANION','DATE','SEASONAL_EVENT',10),
        ('COMPANION','FRIENDS','WORKSHOP',10), ('COMPANION','FRIENDS','PLAY',25), ('COMPANION','FRIENDS','SPORT',20), ('COMPANION','FRIENDS','OUTDOOR',5), ('COMPANION','FRIENDS','SHOPPING',15), ('COMPANION','FRIENDS','HEALING',5), ('COMPANION','FRIENDS','SEASONAL_EVENT',5),
        ('COMPANION','FAMILY','CULTURE',15), ('COMPANION','FAMILY','OUTDOOR',20), ('COMPANION','FAMILY','SHOPPING',10), ('COMPANION','FAMILY','HEALING',10), ('COMPANION','FAMILY','SEASONAL_EVENT',20),
        ('COMPANION','SOLO','CULTURE',15), ('COMPANION','SOLO','OUTDOOR',20), ('COMPANION','SOLO','SHOPPING',10), ('COMPANION','SOLO','HEALING',20),
        ('COMPANION','COLLEAGUES','CULTURE',10), ('COMPANION','COLLEAGUES','PLAY',20), ('COMPANION','COLLEAGUES','SHOPPING',10),
        ('OCCASION','CASUAL_OUTING','PLAY',10), ('OCCASION','CASUAL_OUTING','OUTDOOR',20), ('OCCASION','CASUAL_OUTING','SHOPPING',10), ('OCCASION','CASUAL_OUTING','HEALING',10),
        ('OCCASION','SPECIAL_OCCASION','CULTURE',15), ('OCCASION','SPECIAL_OCCASION','WORKSHOP',25), ('OCCASION','SPECIAL_OCCASION','PLAY',10), ('OCCASION','SPECIAL_OCCASION','SHOPPING',10), ('OCCASION','SPECIAL_OCCASION','HEALING',15), ('OCCASION','SPECIAL_OCCASION','SEASONAL_EVENT',20),
        ('OCCASION','TOURISM','CULTURE',20), ('OCCASION','TOURISM','OUTDOOR',15), ('OCCASION','TOURISM','SHOPPING',10), ('OCCASION','TOURISM','SEASONAL_EVENT',25),
        ('ENVIRONMENT','INDOOR','CULTURE',15), ('ENVIRONMENT','INDOOR','WORKSHOP',20), ('ENVIRONMENT','INDOOR','PLAY',20), ('ENVIRONMENT','INDOOR','SPORT',15), ('ENVIRONMENT','INDOOR','SHOPPING',20), ('ENVIRONMENT','INDOOR','HEALING',20),
        ('ENVIRONMENT','OUTDOOR','SPORT',15), ('ENVIRONMENT','OUTDOOR','OUTDOOR',25), ('ENVIRONMENT','OUTDOOR','SHOPPING',5), ('ENVIRONMENT','OUTDOOR','SEASONAL_EVENT',20),
        ('ENERGY','QUIET','CULTURE',20), ('ENERGY','QUIET','WORKSHOP',10), ('ENERGY','QUIET','OUTDOOR',10), ('ENERGY','QUIET','HEALING',25),
        ('ENERGY','RELAXED','CULTURE',10), ('ENERGY','RELAXED','WORKSHOP',10), ('ENERGY','RELAXED','OUTDOOR',15), ('ENERGY','RELAXED','HEALING',25),
        ('ENERGY','ACTIVE','WORKSHOP',10), ('ENERGY','ACTIVE','PLAY',20), ('ENERGY','ACTIVE','SPORT',25), ('ENERGY','ACTIVE','OUTDOOR',20),
        ('ENERGY','LIVELY','PLAY',25), ('ENERGY','LIVELY','SPORT',15), ('ENERGY','LIVELY','SHOPPING',15), ('ENERGY','LIVELY','SEASONAL_EVENT',20),
        ('HIGHLIGHT','CONVERSATION','CULTURE',10), ('HIGHLIGHT','CONVERSATION','WORKSHOP',10), ('HIGHLIGHT','CONVERSATION','OUTDOOR',10), ('HIGHLIGHT','CONVERSATION','HEALING',20),
        ('HIGHLIGHT','UNIQUE_EXPERIENCE','CULTURE',10), ('HIGHLIGHT','UNIQUE_EXPERIENCE','WORKSHOP',25), ('HIGHLIGHT','UNIQUE_EXPERIENCE','PLAY',15), ('HIGHLIGHT','UNIQUE_EXPERIENCE','SPORT',10), ('HIGHLIGHT','UNIQUE_EXPERIENCE','SEASONAL_EVENT',20),
        ('HIGHLIGHT','SIGHTS_AND_PHOTOS','CULTURE',25), ('HIGHLIGHT','SIGHTS_AND_PHOTOS','OUTDOOR',20), ('HIGHLIGHT','SIGHTS_AND_PHOTOS','SHOPPING',10), ('HIGHLIGHT','SIGHTS_AND_PHOTOS','HEALING',15), ('HIGHLIGHT','SIGHTS_AND_PHOTOS','SEASONAL_EVENT',15),
        ('HIGHLIGHT','TRENDY_PLACES','CULTURE',15), ('HIGHLIGHT','TRENDY_PLACES','WORKSHOP',10), ('HIGHLIGHT','TRENDY_PLACES','PLAY',10), ('HIGHLIGHT','TRENDY_PLACES','SHOPPING',25), ('HIGHLIGHT','TRENDY_PLACES','SEASONAL_EVENT',20),
        ('DATE_MOOD','ROMANTIC','CULTURE',20), ('DATE_MOOD','ROMANTIC','WORKSHOP',25), ('DATE_MOOD','ROMANTIC','HEALING',10),
        ('DATE_MOOD','RELAXED','CULTURE',10), ('DATE_MOOD','RELAXED','OUTDOOR',10), ('DATE_MOOD','RELAXED','HEALING',20),
        ('DATE_MOOD','ACTIVE','WORKSHOP',10), ('DATE_MOOD','ACTIVE','PLAY',15), ('DATE_MOOD','ACTIVE','SPORT',20), ('DATE_MOOD','ACTIVE','OUTDOOR',15)
) AS rule_seed(preference_group_code, preference_option_code, activity_category_code, weight)
JOIN preference_groups preference_group ON preference_group.code = rule_seed.preference_group_code
JOIN preference_options preference_option ON preference_option.preference_group_id = preference_group.id
    AND preference_option.code = rule_seed.preference_option_code
JOIN activity_categories activity_category ON activity_category.code = rule_seed.activity_category_code;

CREATE TABLE course_anchors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    anchor_type VARCHAR(20) NOT NULL,
    parent_region_name VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    radius_meters INTEGER NOT NULL,
    display_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_course_anchors_code UNIQUE (code),
    CONSTRAINT ck_course_anchors_type CHECK (anchor_type IN ('AREA', 'HUB')),
    CONSTRAINT ck_course_anchors_radius CHECK (radius_meters > 0),
    CONSTRAINT ck_course_anchors_display_order CHECK (display_order >= 0)
);

CREATE TABLE course_anchor_activity_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_anchor_id BIGINT NOT NULL,
    activity_category_id BIGINT NOT NULL,
    weight INTEGER NOT NULL,
    CONSTRAINT fk_course_anchor_activity_rules_anchor
        FOREIGN KEY (course_anchor_id) REFERENCES course_anchors (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_anchor_activity_rules_activity_category
        FOREIGN KEY (activity_category_id) REFERENCES activity_categories (id),
    CONSTRAINT uk_course_anchor_activity_rules_anchor_category
        UNIQUE (course_anchor_id, activity_category_id)
);

CREATE TABLE course_anchor_preference_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_anchor_id BIGINT NOT NULL,
    preference_option_id BIGINT NOT NULL,
    weight INTEGER NOT NULL,
    CONSTRAINT fk_course_anchor_preference_rules_anchor
        FOREIGN KEY (course_anchor_id) REFERENCES course_anchors (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_anchor_preference_rules_preference_option
        FOREIGN KEY (preference_option_id) REFERENCES preference_options (id),
    CONSTRAINT uk_course_anchor_preference_rules_anchor_option
        UNIQUE (course_anchor_id, preference_option_id)
);

CREATE INDEX idx_course_anchors_region_active_order
    ON course_anchors (parent_region_name, is_active, display_order);

CREATE INDEX idx_course_anchor_activity_rules_category_anchor
    ON course_anchor_activity_rules (activity_category_id, course_anchor_id);

CREATE INDEX idx_course_anchor_preference_rules_option_anchor
    ON course_anchor_preference_rules (preference_option_id, course_anchor_id);

INSERT INTO course_anchors (
    code, anchor_type, parent_region_name, name, description,
    latitude, longitude, radius_meters, display_order
)
VALUES
    ('SEONGSU', 'AREA', '서울', '성수동', '전시·팝업·편집샵을 함께 즐기기 좋은 성수동 중심 코스', 37.5446, 127.0557, 2000, 1),
    ('SEOCHON', 'AREA', '서울', '서촌', '전시·산책·문화 공간을 둘러보기 좋은 서촌 중심 코스', 37.5791, 126.9698, 1500, 2),
    ('HONGDAE_YEONNAM', 'AREA', '서울', '홍대·연남', '쇼핑·놀이·팝업을 함께 즐기기 좋은 홍대·연남 중심 코스', 37.5563, 126.9236, 2500, 3),
    ('ITAEWON', 'AREA', '서울', '이태원', '식사·쇼핑·이색적인 문화를 즐기기 좋은 이태원 중심 코스', 37.5345, 126.9946, 2000, 4),
    ('IPARK_MALL', 'HUB', '서울', '아이파크몰', '영화·쇼핑·식사를 한곳에서 연결하기 좋은 아이파크몰 중심 코스', 37.5298, 126.9647, 1500, 5),
    ('COEX', 'HUB', '서울', '코엑스', '전시·영화·쇼핑을 실내에서 즐기기 좋은 코엑스 중심 코스', 37.5126, 127.0589, 1500, 6),
    ('THE_HYUNDAI_SEOUL', 'HUB', '서울', '더현대 서울', '쇼핑·팝업·식사를 연결하기 좋은 더현대 서울 중심 코스', 37.5258, 126.9287, 1500, 7);

INSERT INTO course_anchor_activity_rules (course_anchor_id, activity_category_id, weight)
SELECT course_anchor.id, activity_category.id, rule_seed.weight
FROM (
    VALUES
        ('SEONGSU', 'CULTURE', 20), ('SEONGSU', 'WORKSHOP', 15), ('SEONGSU', 'SHOPPING', 25), ('SEONGSU', 'SEASONAL_EVENT', 25),
        ('SEOCHON', 'CULTURE', 25), ('SEOCHON', 'OUTDOOR', 15), ('SEOCHON', 'SHOPPING', 10), ('SEOCHON', 'SEASONAL_EVENT', 10),
        ('HONGDAE_YEONNAM', 'CULTURE', 10), ('HONGDAE_YEONNAM', 'PLAY', 20), ('HONGDAE_YEONNAM', 'SHOPPING', 25), ('HONGDAE_YEONNAM', 'SEASONAL_EVENT', 20),
        ('ITAEWON', 'CULTURE', 10), ('ITAEWON', 'PLAY', 15), ('ITAEWON', 'SHOPPING', 20), ('ITAEWON', 'SEASONAL_EVENT', 15),
        ('IPARK_MALL', 'CULTURE', 10), ('IPARK_MALL', 'PLAY', 15), ('IPARK_MALL', 'SHOPPING', 25), ('IPARK_MALL', 'HEALING', 5),
        ('COEX', 'CULTURE', 10), ('COEX', 'PLAY', 20), ('COEX', 'SHOPPING', 25), ('COEX', 'SEASONAL_EVENT', 15),
        ('THE_HYUNDAI_SEOUL', 'CULTURE', 10), ('THE_HYUNDAI_SEOUL', 'SHOPPING', 25), ('THE_HYUNDAI_SEOUL', 'HEALING', 5), ('THE_HYUNDAI_SEOUL', 'SEASONAL_EVENT', 25)
) AS rule_seed(course_anchor_code, activity_category_code, weight)
JOIN course_anchors course_anchor ON course_anchor.code = rule_seed.course_anchor_code
JOIN activity_categories activity_category ON activity_category.code = rule_seed.activity_category_code;

INSERT INTO course_anchor_preference_rules (course_anchor_id, preference_option_id, weight)
SELECT course_anchor.id, preference_option.id, rule_seed.weight
FROM (
    VALUES
        ('SEONGSU', 'ENVIRONMENT', 'INDOOR', 5), ('SEONGSU', 'ENVIRONMENT', 'OUTDOOR', 10),
        ('SEONGSU', 'ENERGY', 'QUIET', 5), ('SEONGSU', 'ENERGY', 'RELAXED', 10), ('SEONGSU', 'ENERGY', 'ACTIVE', 15), ('SEONGSU', 'ENERGY', 'LIVELY', 15),
        ('SEONGSU', 'HIGHLIGHT', 'CONVERSATION', 10), ('SEONGSU', 'HIGHLIGHT', 'UNIQUE_EXPERIENCE', 15), ('SEONGSU', 'HIGHLIGHT', 'SIGHTS_AND_PHOTOS', 20), ('SEONGSU', 'HIGHLIGHT', 'TRENDY_PLACES', 25),
        ('SEONGSU', 'DATE_MOOD', 'ROMANTIC', 15), ('SEONGSU', 'DATE_MOOD', 'RELAXED', 10), ('SEONGSU', 'DATE_MOOD', 'ACTIVE', 15),
        ('SEOCHON', 'ENVIRONMENT', 'OUTDOOR', 20), ('SEOCHON', 'ENERGY', 'QUIET', 20), ('SEOCHON', 'ENERGY', 'RELAXED', 15),
        ('SEOCHON', 'HIGHLIGHT', 'CONVERSATION', 15), ('SEOCHON', 'HIGHLIGHT', 'UNIQUE_EXPERIENCE', 10), ('SEOCHON', 'HIGHLIGHT', 'SIGHTS_AND_PHOTOS', 20),
        ('SEOCHON', 'DATE_MOOD', 'ROMANTIC', 20), ('SEOCHON', 'DATE_MOOD', 'RELAXED', 15),
        ('HONGDAE_YEONNAM', 'ENVIRONMENT', 'OUTDOOR', 10), ('HONGDAE_YEONNAM', 'ENERGY', 'ACTIVE', 15), ('HONGDAE_YEONNAM', 'ENERGY', 'LIVELY', 25),
        ('HONGDAE_YEONNAM', 'HIGHLIGHT', 'UNIQUE_EXPERIENCE', 15), ('HONGDAE_YEONNAM', 'HIGHLIGHT', 'SIGHTS_AND_PHOTOS', 10), ('HONGDAE_YEONNAM', 'HIGHLIGHT', 'TRENDY_PLACES', 20), ('HONGDAE_YEONNAM', 'DATE_MOOD', 'ACTIVE', 20),
        ('ITAEWON', 'ENVIRONMENT', 'OUTDOOR', 15), ('ITAEWON', 'ENERGY', 'ACTIVE', 15), ('ITAEWON', 'ENERGY', 'LIVELY', 15),
        ('ITAEWON', 'HIGHLIGHT', 'UNIQUE_EXPERIENCE', 20), ('ITAEWON', 'HIGHLIGHT', 'SIGHTS_AND_PHOTOS', 10), ('ITAEWON', 'HIGHLIGHT', 'TRENDY_PLACES', 15), ('ITAEWON', 'DATE_MOOD', 'ROMANTIC', 15), ('ITAEWON', 'DATE_MOOD', 'ACTIVE', 15),
        ('IPARK_MALL', 'COMPANION', 'FAMILY', 15), ('IPARK_MALL', 'ENVIRONMENT', 'INDOOR', 25), ('IPARK_MALL', 'ENERGY', 'RELAXED', 5), ('IPARK_MALL', 'HIGHLIGHT', 'CONVERSATION', 5),
        ('COEX', 'COMPANION', 'FAMILY', 15), ('COEX', 'ENVIRONMENT', 'INDOOR', 25), ('COEX', 'ENERGY', 'LIVELY', 10), ('COEX', 'HIGHLIGHT', 'SIGHTS_AND_PHOTOS', 10), ('COEX', 'HIGHLIGHT', 'TRENDY_PLACES', 10),
        ('THE_HYUNDAI_SEOUL', 'COMPANION', 'FAMILY', 10), ('THE_HYUNDAI_SEOUL', 'ENVIRONMENT', 'INDOOR', 25), ('THE_HYUNDAI_SEOUL', 'ENERGY', 'RELAXED', 10), ('THE_HYUNDAI_SEOUL', 'HIGHLIGHT', 'SIGHTS_AND_PHOTOS', 15), ('THE_HYUNDAI_SEOUL', 'HIGHLIGHT', 'TRENDY_PLACES', 20)
) AS rule_seed(course_anchor_code, preference_group_code, preference_option_code, weight)
JOIN course_anchors course_anchor ON course_anchor.code = rule_seed.course_anchor_code
JOIN preference_groups preference_group ON preference_group.code = rule_seed.preference_group_code
JOIN preference_options preference_option ON preference_option.preference_group_id = preference_group.id
    AND preference_option.code = rule_seed.preference_option_code;
