CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selected_region_name VARCHAR(100) NOT NULL,
    selected_region_latitude NUMERIC(10, 7) NOT NULL,
    selected_region_longitude NUMERIC(10, 7) NOT NULL,
    selected_region_radius_meters INTEGER NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SAVED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_courses_selected_region_radius
        CHECK (selected_region_radius_meters > 0),
    CONSTRAINT ck_courses_schedule_range
        CHECK (ends_at > scheduled_at),
    CONSTRAINT ck_courses_status
        CHECK (status IN ('SAVED', 'ARCHIVED'))
);

CREATE TABLE course_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    preference_option_id BIGINT NOT NULL,
    CONSTRAINT fk_course_preferences_course
        FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_preferences_preference_option
        FOREIGN KEY (preference_option_id) REFERENCES preference_options (id),
    CONSTRAINT uk_course_preferences_course_option
        UNIQUE (course_id, preference_option_id)
);

CREATE TABLE course_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    sequence_no INTEGER NOT NULL,
    item_type VARCHAR(20) NOT NULL,
    place_id BIGINT NOT NULL,
    CONSTRAINT fk_course_items_course
        FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_items_place
        FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT uk_course_items_course_sequence
        UNIQUE (course_id, sequence_no),
    CONSTRAINT ck_course_items_sequence
        CHECK (sequence_no > 0),
    CONSTRAINT ck_course_items_type
        CHECK (item_type IN ('ACTIVITY', 'MEAL', 'CAFE', 'OTHER'))
);

CREATE INDEX idx_courses_status_created_at
    ON courses (status, created_at DESC);

CREATE INDEX idx_course_items_course_sequence
    ON course_items (course_id, sequence_no);
